config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'
  
  resources :employees do
    collection do
     post :add_contact
     post :delete_number
    end
  end
  resources :departments
  # get 'employees/new'
  # get 'employees/create'
  # get 'employees/update'
  # get 'employees/edit'
  # get 'employees/destroy'
  # get 'employees/index'
  # get 'employees/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :employees
	validates :name, presence: :true 
	validates_uniqueness_of :name ,on: :create
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :phone_numbers, :dependent => :destroy
	belongs_to :department
	accepts_nested_attributes_for :phone_numbers
    validates :name, :address,:salute,:base_salary,:da,:ta,:dob,:sex,presence: true ,on: :create
    validates :name, :address,:salute,:base_salary,:da,:ta,:dob,:sex,presence: true ,on: :update
    validates_associated :phone_numbers
   
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
   @departments = Department.all.order("updated_at desc")
 end

 def new
   @department = Department.new
 end

 def create
    #debugger
    @department = Department.new(department_params)
    respond_to do |format|
    if @department.save
      format.html { redirect_to departments_path ,notice: 'Department was successfully created.'}
   else
     format.html {render :new , notice: "Error in Creatin department" }
   end
 end
  end

  def edit
   @department = Department.find(params[:id])
  end

 def update
    #debugger
    @department = Department.find(params[:id])
    @department.update(department_params)
    redirect_to departments_path
  end

  def destroy
    #debugger
    @department = Department.find(params[:id])
     respond_to do |format|
    if @department.employees.present?
      format.html { redirect_to departments_path ,notice: 'Department have employees so cannot be deleted'}
    else
      @department.destroy
      format.html { redirect_to departments_path ,notice: 'Department Deleted successfully'}
    end
   end
  end

  private

  def department_params
   params.require(:department).permit(:name)
 end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  helper_method :total_salary
  def index
   @employees = Employee.order("updated_at desc").paginate(page: params[:page],per_page: 10)
 end

 def new
  @dep_options = Department.all.map { |d| [ d.name,d.id ] } 
  @employee = Employee.new
end

def create
   # debugger
  @dep_options = Department.all.map { |d| [ d.name,d.id ] } 
   @employee = Employee.new(employee_params)
   if @employee.save
    p_num = params[:employee][:phone_number]
    if p_num.present?
    p_num.each do|p_no| 
      @employee.phone_numbers.create!(phone_num: p_no)
    end
  end
    redirect_to root_path
  else
   render 'new'
 end
end

def edit
 # debugger
  @dep_options = Department.all.map { |d| [ d.name,d.id ] }
 @employee = Employee.find_by_id(params[:id])
end

def update
  #debugger
   @dep_options = Department.all.map { |d| [ d.name,d.id ] }
  @employee = Employee.find_by_id(params[:id])
  if @employee.update(employee_params)
    p_num = params[:employee][:phone_number]
    if p_num.present?
      p_num.each do|p_no| 
        @employee.phone_numbers.create!(phone_num: p_no)
      end
    end
    redirect_to root_path
  else
   render 'edit'
 end
end

def show
end

def destroy
  emp = Employee.find_by_id(params[:id])
  emp.destroy
  redirect_to employees_path
end

def add_contact
 #debugger
end

def delete_number
#debugger
p_num = params[:deletedPhones] 
e1 = Employee.find(params[:id])
if p_num.present? && e1.present?
 p_num.each do|p_number|
  e1.phone_numbers.find_by_phone_num(p_number).destroy  
end
end
render json: {status: 'ok', message: "proceed" }
end

private

def total_salary(sal,da,ta)
  if sal.present? && da.present? && ta.present?
    d_allowance = (sal*da)/100
    t_allowance = (sal*ta)/100
    return sal+d_allowance+t_allowance
  end
end


def employee_params
 params.require(:employee).permit(:name,:base_salary,:address,:department_id,:dob,:da,:ta,:salute,:sex,phone_numbers_attributes: [:id,:phone_num])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end

end

app/helpers/employees_helper.rb
module EmployeesHelper
	
end

app/views/departments/_sidbar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-user-crown"></i></span>
          <%= link_to 'Employee',root_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-list-alt" aria-hidden="true"></i></span>
          <%= link_to "Department",departments_path ,class: "nav-link"%>
        </li>
        
  </ul>
</div>

app/views/departments/edit.html.erb
<div class="topBar skin-primary">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col-md-4">
				<div class="logo">
					<span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
						<i class="fa fa-bars"></i>
					</span>

					<a href="/" class="logo-icon text-dark">
						<!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
						<span class="ft-dark-black">Employee Management</span>
					</a>
				</div>
			</div>
			<div class="col-md-4">
				<!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
			</div>
			<div class="col-md-4 text-right">
				<!-- Example split danger button -->
				<div class="btn-group mt-2">
					<%= link_to 'Back', root_path, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
					<button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="sr-only">Toggle Dropdown</span>
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="changePassword.php">Change Password</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="index.php">Logout</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render 'sidbar' %>

<section class="wrap page-addVendors">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<div class="block bx-shadow">
				<div class="content v-form skin-light">
					<div class="row">
						<div class="col-md-12">
							<div class="page-header">
								<h4>Edit Department</h4>
							</div>  
						</div>
					</div>

					<div class="container col-md-8">
						<%= bootstrap_form_for(@department) do |f| %>

						<%= f.text_field :name %>

						<%= f.submit "Update Department", class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/departments/index.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>

    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%= link_to 'Back', root_path, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidbar' %>
<div class="row">
 <div class="col-md-12">
  <div class="page-header"  style="margin-top: 5%">
   <%= link_to 'Add department', new_department_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
 </div>
</div>
</div>
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-9 offset-md-2">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
         <div class="content">
           <table id="example" class="table table-striped">
             <thead>
               <tr>
                 <th>Department Name</th>
               </tr>
             </thead>
             <tbody>
              <% @departments.each do |dep| %>
              <tr>
                <td><%= dep.name %></td>   <br>
                <td>
                 <%= link_to edit_department_path(dep) ,class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
                 <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                 <% end %>
                 
                 <%= link_to  department_path(dep) , method: :delete, data: { confirm: "Are you sure?" },class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
                 <i class="fa fa-trash"></i>
                 <% end %>
               </td>
             </tr>
             <% end %>

           </tbody>
         </table>
       </div>
     </div>
   </div>
 </div>
</section>

app/views/departments/new.html.erb
<div class="topBar skin-primary">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col-md-4">
				<div class="logo">
					<span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
						<i class="fa fa-bars"></i>
					</span>

					<a href="/" class="logo-icon text-dark">
						<!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
						<span class="ft-dark-black">Employee Management</span>
					</a>
				</div>
			</div>
			<div class="col-md-4">
				<!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
			</div>
			<div class="col-md-4 text-right">
				<!-- Example split danger button -->
				<div class="btn-group mt-2">
					<%= link_to 'Back', root_path, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
					<button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span class="sr-only">Toggle Dropdown</span>
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="changePassword.php">Change Password</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="index.php">Logout</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render 'sidbar' %>

<section class="wrap page-addVendors">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<div class="block bx-shadow">
				<div class="content v-form skin-light">
					<div class="row">
						<div class="col-md-12">
							<div class="page-header">
								<h4>Create Employee</h4>
							</div>  
						</div>
					</div>

					<div class="container col-md-8">
						<%= bootstrap_form_for(@department) do |f| %>
						<%= f.text_field :name %>
						<%= f.submit "Create Derpartment",class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/employees/_sidebar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-tachometer-alt" aria-hidden="true"></i></span>
          <%= link_to 'Employee',root_path ,class: "nav-link"%>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-list-alt" aria-hidden="true"></i></span>
          <%= link_to "Department",departments_path ,class: "nav-link"%>
        </li>
        
  </ul>
</div>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>
    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%= link_to 'Back', root_path, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>
</div>
<%= render 'sidebar' %>
<!-- page-content -->
<section class="wrap page-addVendors">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="block bx-shadow">
        <div class="content v-form skin-light">
          <div class="row">
            <div class="col-md-12">
              <div class="page-header">
                <h4>Edit Employee</h4>
              </div>  
            </div>
          </div>

          <div class="container col-md-8">
            <%= bootstrap_form_for(@employee) do |f| %>
            <% if @employee.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @employee.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <%= f.select :salute, (["Mr","Miss"])%>
            <%= f.text_field :name,class: 'form-control'%>
            <%= f.select(:department_id, @dep_options,{:include_blank => true})%>
            <%= f.label "Gender" %><br>
            <%= f.radio_button :sex,'male'  %>   
            <%= f.radio_button :sex,'female' %><br>
            <%= f.date_field :dob  %>
            <div class="field_wrapper">
              <div> 
                Add Phone <br> <a href="javascript:void(0);" class="add_button" title="Add field"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a>
                <br>
                <% i = 0 %>   
                <%= f.nested_fields_for :phone_numbers do |numbers_form  | %>
                <% i+=1%>     
                <%= numbers_form.text_field :phone_num, class: "phone-number" + i.to_s %>
                <a href="javascript:void(0);" class="remove_button"> <i type='button' class="fa fa-minus-circle fa-2x" aria-hidden="true" id="btn-delete-phone" data-id='<%= i %>'></i></a>
                <!--  <button type='button' id="btn-delete-phone" data-id='<%= i %>' class="btn btn-info">X</button>  -->
                <% end %> 


              </div>
            </div><br>
            <%= f.text_field :base_salary %><br>
            <%= f.select :da, ((0..20).map {|i| [i,i] }) %><br>
            <%= f.select :ta, ((0..15).map {|i| [i,i] }) %><br>
            <%= f.text_area :address, class: 'form-control' %><br>
            <%= f.submit "Update Employee" ,class: 'v-btn v-btn-primary btn-sm btn-shadow'%>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
 var deletedPhones = [];
 $(document).ready(function(){
    var maxField = 10; //Input fields increment limitation
    var addButton = $('.add_button'); //Add button selector
    var wrapper = $('.field_wrapper'); //Input field wrapper
    var btnDelete = $('#btn-delete-phone');
    var fieldHTML = '<div><input type="text" name="employee[phone_number][]" value=""/><a href="javascript:void(0);" class="remove_button"> <i class="fa fa-minus-circle fa-2x" aria-hidden="true"></i></a></div>'; //New input field html 
    var x = 1; //Initial field counter is 1
    
    //Once add button is clicked
    $(addButton).click(function(){
        //Check maximum number of input fields
        if(x < maxField){ 
            x++; //Increment field counter
            $(wrapper).append(fieldHTML); //Add field html
          }
        });
    
    //Once remove button is clicked
    $(wrapper).on('click', '.remove_button', function(e){
      e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        x--; //Decrement field counter
      });

    $(wrapper).on('click', '#btn-delete-phone',deletePhone);

  });

 var deletePhone = function(){
  var $btnDelete = $(this);
  var id = $btnDelete.data('id');
  var $phone = $('.phone-number'+id);
  var phone = $phone.val();
  deletedPhones.push(phone);
  var fieldset = $(this).closest('fieldset'); 
  if(fieldset)
  {
    fieldset.remove();
  }
  // $phone.hide();
  removeNumber(phone);

}

var removeNumber = function(number){
 $.ajax({
   type: "POST",
   beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))}, 
   url: "/employees/delete_number",
   data: {deletedPhones: [number], id: '<%= @employee.id %>'},
   dataType: "json",
   success: function(data, textStatus, jqXHR){
    // location.reload();
  },
  error: function(jqXHR, textStatus, errorThrown){
    console.log(errorThrown);
  }
});
}
</script>

app/views/employees/index.html.erb
<div class="topBar skin-primary">
 <div class="container-fluid">
  <div class="row align-items-center">
   <div class="col-md-4">
    <div class="logo">
     <span href="javascript:void(0)" class="toggle-sideBar icon icon-md ft-dark">
      <i class="fa fa-bars"></i>
    </span>

    <a href="/" class="logo-icon text-dark">
     <!--<img src="img/simplusLogo.png" alt="simplus" class="" style="width: 120px">-->
     <span class="ft-dark-black">Employee Management</span>
   </a>
 </div>
</div>
<div class="col-md-4">
  <!--<h4 class="text-center text-white fw-600 uppercase mt-2">Dashboard</h4>-->
</div>
<div class="col-md-4 text-right">
  <!-- Example split danger button -->
  <div class="btn-group mt-2">
    <%=  link_to "Logout", destroy_user_session_path, method: :delete, class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow" %>
    <button type="button" class="v-btn v-btn-dark btn-sm no-round dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="changePassword.php">Change Password</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="index.php">Logout</a>
    </div>
  </div>
</div>
</div>
</div>

</div>



<%= render 'sidebar' %>
<!-- page-content -->
<div class="row">
 <div class="col-md-12">
  <div class="page-header"  style="margin-top: 5%">
   <%= link_to 'Add Employee', new_employee_path ,class: "v-btn v-btn-primary btn-sm no-round float-right btn-shadow"%>
 </div>
</div>
</div>

<section class="wrap page-addVendors">
 <div class="row">
   <div class="col-md-9 offset-md-2">
    <div class="block bx-shadow skin-light">
     <div class="content">
      <table id="example" class="table table-striped">
       <thead>
        <tr>
         <th>Salute</th>
         <th>Name</th>
         <th>Gender </th>
         <th>DOB</th>
         <th>Address</th>
         <th>Salary</th>
         <th>Action</th>
       </tr>
     </thead>
     <tbody>
       <% @employees.each do |emp| %>
       <tr>
         <% if emp.present? %>
         <td><%= emp.salute %></td>
         <td><%= emp.name %> </td>
         <td><%= emp.sex %></td>
         <td><%= emp.dob.strftime("%b/%d/%Y") %></td>
         <td><%= emp.address %></td>
         <td><%= total_salary(emp.base_salary,emp.da,emp.ta) %></td>
         <% end %>
         <td>
           <%= link_to edit_employee_path(emp) ,class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
           <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
           <% end %>
           
           <%= link_to  employee_path(emp) , method: :delete, data: { confirm: "Are you sure?" },class: 'v-btn v-btn-transparent ft-primary icon icon-xs uppercase' do %>
           <i class="fa fa-trash"></i>
           <% end %>
         </td>
       </td>
     </tr>
     <% end %>
   </tbody>
 </table>
</div>
</div>
</div>
</div>
</div>
</div>
<%= will_paginate @employees, renderer: WillPaginateSemanticUi::ActionView::Renderer, class: "right floated", inner_window: 3 %>
</div>
</section>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Find me in app/views/employees/show.html.erb</p>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomerMng</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <%= yield %>
</body>
</html>

app/views/shared/_sidebar.html.erb
 <div class="asside-panel assideNav-panel fixed left top bottom animate scrollbar scroll-y">
  <ul class="list nav-list">
    
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-tachometer-alt" aria-hidden="true"></i></span>
          <a href="#" class="nav-link " title="Reports">Dashboard</a>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-list-alt" aria-hidden="true"></i></span>
          <a href="#" class="nav-link " title="Incidents">Incidents </a>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-users" aria-hidden="true"></i></span>
          <a href="#" class="nav-link " title="Incidents">Users </a>
        </li>
        <li class="nav-item">
          <span class="icon icon-sm nav-icon inline"><i class="fa fa-file" aria-hidden="true"></i></span>
          <a href="#" class="nav-link " title="Incidents">Invoice Deduction </a>
        </li>
  </ul>
</div>